### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by rgreinho** [PeopleForBikes/PeopleForBikes.github.io#26]
# Feature request

## Current Behavior

We currently use the BNA logos.

## Expected Behavior

Now that we are starting to have our own identity, we should use the BNA logos.

**Comment by lalver1** [comment]
Sorry Remy, I just submitted a PR for the logo update but overlooked that we had an open issue and I didn't tag the PR with it.

**Comment by rgreinho** [comment]
Closing since @lalver1 resolved it.
